---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-event
  description: Some description of the event component
  tags:
  - event
  links:
    - title: Repository
      description: GitHub repository
      url: https://github.com/mmussett/developer-hub-eda
    - title: VSCode
      description: Edit in VSCode
      url: vscode://vscode.git/clone?url=https://github.com/mmussett/flogo-hello-world-event-driven/component-events.yaml
    - title: Schema
      description: Schema
      url: https://github.com/mmussett/flogo-hello-world-event-driven/blob/main/schemas/event.json
spec:
  type: event
  lifecycle: production
  owner: group:kafka-messaging-group
  system: event-driven-system
  ownedBy:
  - component:flogo-hello-world-event-publisher
  partOf:
  - component:flogo-hello-world-event-subscriber
  schema:
    type: json
    ref: https://github.com/mmussett/flogo-hello-world-event-driven/schemas/event.json
