---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: eda-apps
  description: Everything related to Event-Driven Applications
spec:
  owner: group:eda
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-messaging-group
  description: ACME Messaging Group
spec:
  type: department
  profile:
    displayName: ACME Messaging Group
    email: info@acme.com
  parent: group:eda
  children: [kafka-messaging-group, ftl-messaging-group, ems-messaging-group]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: kafka-messaging-group
  description: Kafka Messaging Group
spec:
  type: department
  profile:
    displayName: Kafka Messaging Group
    email: info@acme.com
  parent: acme-messaging-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ftl-messaging-group
  description: TIBCO FTL Messaging Group
spec:
  type: department
  profile:
    displayName: TIBCO FTL Messaging Group
    email: info@acme.com
  parent: acme-messaging-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ems-messaging-group
  description: TIBCO EMS Messaging Group
spec:
  type: department
  profile:
    displayName: TIBCO EMS Messaging Group
    email: info@acme.com
  parent: acme-messaging-group
  children: []