---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: eda-apps
  description: Everything related to Event-Driven Applications
spec:
  owner: group:eda
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tibco-messaging-group
  description: TIBCO Messaging Group
  tags:
    - messaging
    - tibco
    - eda
spec:
  type: department
  profile:
    displayName: TIBCO Messaging Group
    email: messaging@tibco.com
  parent: group:eda
  children: [pulsar-messaging-group, kafka-messaging-group, ftl-messaging-group, ems-messaging-group]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ftl-messaging-group
  description: TIBCO FTL Messaging Group  
  tags:
    - messaging
    - tibco
    - eda
    - ftl
spec:
  type: department
  profile:
    displayName: TIBCO FTL Messaging Group
    email: messaging@tibco.com
  parent: tibco-messaging-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ems-messaging-group
  description: TIBCO EMS Messaging Group
  tags:
    - messaging
    - tibco
    - eda
    - ems
spec:
  type: department
  profile:
    displayName: TIBCO EMS Messaging Group
    email: messaging@tibco.com
  parent: tibco-messaging-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rv-messaging-group
  description: TIBCO Rendezvous Messaging Group
  tags:
    - messaging
    - tibco
    - eda
    - rv
spec:
  type: department
  profile:
    displayName: TIBCO RV Messaging Group
    email: messaging@tibco.com
  parent: tibco-messaging-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: kafka-messaging-group
  description: TIBCO Castle - Kafka Messaging Group
  tags:
    - messaging
    - tibco
    - eda
    - kafka
    - apache
spec:
  type: department
  profile:
    displayName: TIBCO Castle - Kafka Messaging Group
    email: messaging@tibco.com
  parent: tibco-messaging-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pulsar-messaging-group
  description: TIBCO Quasar - Apache Pulsar Messaging Group
  tags:
    - messaging
    - tibco
    - eda
    - kafka
    - pulsar
    - apache
spec:
  type: department
  profile:
    displayName: TIBCO Quasar - Apache Pulsar Messaging Group
    email: messaging@tibco.com
  parent: tibco-messaging-group
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mosquitto-messaging-group
  description: TIBCO Messaging - Apache Mosquitto Messaging Group
  tags:
    - messaging
    - tibco
    - eda
    - mqtt
    - apache
spec:
  type: department
  profile:
    displayName: Apache Mosquitto Messaging Group
    email: messaging@tibco.com
  parent: tibco-messaging-group
  children: []