site_name: 'flogo-hello-world-event-driven'
site_description: 'A simple hello-world event-driven demonstration using Flogo'

nav:
  - Introduction: index.md

  - Schemas: docs/schemas/README.md

plugins:
  - techdocs-core