site_name: 'flogo-hello-world-event-driven'
site_description: 'A simple hello-world event-driven demonstration using Flogo'

nav:
  - Introduction: index.md
  - Schemas: event.schema.md

plugins:
  - techdocs-core